services:
  # Backend API
  - type: web
    name: lineup-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: MODAL_HAIRFAST_ENDPOINT
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    
  # Frontend Static Site
  - type: web
    name: lineup-frontend
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
