"""Virtual try-on: Replicate (FLUX Kontext change-haircut) with a guaranteed
local preview fallback that overlays the style name on the user's photo."""

from __future__ import annotations

import base64
import logging
from io import BytesIO
from typing import Any, Callable, Dict, Optional, Tuple

import requests
from PIL import Image, ImageDraw, ImageFont

from lineup_backend.services.gemini import GeminiService
from lineup_backend.services.haircuts import ALLOWED_HAIRCUTS, keyword_match

logger = logging.getLogger(__name__)

MODEL_REF = "flux-kontext-apps/change-haircut:48f03523665cabe9a2e832ea9cc2d7c30ad5079cb5f1c1f07890d40596fe1f87"
FONT_PATHS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "arial.ttf",
]


class TryOnService:
    def __init__(
        self,
        replicate_token: Optional[str],
        gemini: GeminiService,
        http_get: Optional[Callable[..., Any]] = None,
        run: Optional[Callable[..., Any]] = None,
    ) -> None:
        self.gemini = gemini
        self._http_get = http_get
        self._run = run
        self._client = None
        if replicate_token and run is None:
            try:
                import replicate

                self._client = replicate.Client(api_token=replicate_token)
                logger.info("Replicate configured for virtual try-on")
            except Exception as exc:  # noqa: BLE001
                logger.warning("Replicate unavailable (%s); try-on uses preview mode", type(exc).__name__)
        elif not replicate_token:
            logger.warning("REPLICATE_API_TOKEN not set: virtual try-on uses preview mode")

    @property
    def available(self) -> bool:
        return self._run is not None or self._client is not None

    def resolve_haircut(self, description: str) -> Tuple[str, str]:
        """Return (haircut name from the model vocabulary, how it was chosen)."""
        if self.gemini.available:
            match = self.gemini.match_haircut(description, ALLOWED_HAIRCUTS)
            if match:
                return match, "gemini"
        match = keyword_match(description)
        if match:
            return match, "keyword"
        return "Random", "fallback"

    def transform(self, image_bytes: bytes, original_b64: str, description: str) -> Dict[str, Any]:
        haircut, method = self.resolve_haircut(description)
        reason = "replicate_not_configured"
        if self.available:
            try:
                result_b64 = self._run_replicate(original_b64, haircut)
                return {
                    "success": True,
                    "message": f"Hair transformation complete: {description}",
                    "originalImage": original_b64,
                    "resultImage": result_b64,
                    "styleApplied": description,
                    "haircut": haircut,
                    "haircutMatchedBy": method,
                    "poweredBy": "Replicate FLUX.1 Kontext (change-haircut)",
                    "note": "Generated by an image model.",
                    "mode": "replicate",
                    "mock": False,
                }
            except Exception as exc:  # noqa: BLE001
                logger.error("Replicate try-on failed, using preview: %s", exc)
                reason = "replicate_error"

        preview_b64 = self.preview_image(image_bytes, description)
        return {
            "success": True,
            "message": f"Style preview created: {description}",
            "originalImage": original_b64,
            "resultImage": preview_b64,
            "styleApplied": description,
            "haircut": haircut,
            "haircutMatchedBy": method,
            "poweredBy": "LineUp preview mode",
            "note": "Preview only: your photo labelled with the style. Configure REPLICATE_API_TOKEN for a generated result.",
            "mode": "preview",
            "mock": True,
            "reason": reason,
        }

    def _run_replicate(self, original_b64: str, haircut: str) -> str:
        runner = self._run or self._client.run
        output = runner(
            MODEL_REF,
            input={
                "input_image": f"data:image/jpeg;base64,{original_b64}",
                "haircut": haircut,
                "aspect_ratio": "match_input_image",
                "output_format": "png",
                "safety_tolerance": 2,
            },
        )
        url = self._extract_url(output)
        if not url:
            raise RuntimeError("Model produced no output URL")
        getter = self._http_get or requests.get
        response = getter(url, timeout=60)
        if getattr(response, "status_code", 500) != 200:
            raise RuntimeError(f"Failed to download result: HTTP {getattr(response, 'status_code', '?')}")
        content = response.content
        if not content or len(content) < 100:
            raise RuntimeError("Invalid image data from model")
        return base64.b64encode(content).decode("utf-8")

    @classmethod
    def _extract_url(cls, output: Any) -> Optional[str]:
        if output is None:
            return None
        if hasattr(output, "url"):
            return str(output.url)
        if isinstance(output, str):
            return output
        if isinstance(output, (list, tuple)):
            return cls._extract_url(output[0]) if output else None
        if hasattr(output, "__iter__"):
            for item in output:
                return cls._extract_url(item)
            return None
        return str(output)

    @staticmethod
    def preview_image(image_bytes: bytes, description: str) -> str:
        """Return a JPEG (base64) of the photo with a labelled band at the bottom."""
        img = Image.open(BytesIO(image_bytes)).convert("RGBA")
        width, height = img.size
        band = max(40, min(70, height // 6))
        overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
        ImageDraw.Draw(overlay).rectangle([(0, height - band), (width, height)], fill=(0, 0, 0, 200))
        img = Image.alpha_composite(img, overlay).convert("RGB")

        draw = ImageDraw.Draw(img)
        text = f"Preview: {description}"
        font = None
        for path in FONT_PATHS:
            try:
                font = ImageFont.truetype(path, max(12, min(28, band // 2)))
                break
            except OSError:
                continue
        if font is None:
            font = ImageFont.load_default()
        try:
            bbox = draw.textbbox((0, 0), text, font=font)
            text_width = bbox[2] - bbox[0]
        except AttributeError:
            text_width = len(text) * 10
        x = max(4, (width - text_width) // 2)
        y = max(4, height - band + (band - 20) // 2)
        draw.text((x + 1, y + 1), text, fill=(0, 0, 0), font=font)
        draw.text((x, y), text, fill=(255, 255, 255), font=font)

        buffer = BytesIO()
        img.save(buffer, format="JPEG", quality=90, optimize=True)
        return base64.b64encode(buffer.getvalue()).decode("utf-8")
